services:
  backend:
    build:
      context: backend
      dockerfile: ../backend/Dockerfile
    ports:
      - '8000:5000'

  frontend:
    build:
      context: frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - '3000:5173'
    depends_on:
      - backend

  redis:
    image: 'redis:alpine'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
